service: serverless-web3-auth

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage,'staging'}

  environment:
    NODE_ENV: production
    JWT_SECRET: ${env:JWT_SECRET, 'your-default-secret-key'}
    JWT_EXPIRATION: ${env:JWT_EXPIRATION, '24h'}
    DB_HOST: ${cf:web3-auth-infra-${self:provider.stage}.DatabaseEndpoint}
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD: ${env:DB_PASSWORD, 'MySecurePassword123!'}
    DB_DATABASE: web3_auth_db
    DB_SYNC: true
    REDIS_HOST: ${cf:web3-auth-infra-${self:provider.stage}.RedisEndpoint}
    REDIS_PORT: 6379
    REDIS_PASSWORD: ${env:REDIS_PASSWORD, ''}

  iam:
    role: ${cf:web3-auth-infra-${self:provider.stage}.LambdaExecutionRoleArn}

  vpc:
    securityGroupIds:
      - ${cf:web3-auth-infra-${self:provider.stage}.AppSecurityGroupId}
    subnetIds:
      - ${cf:web3-auth-infra-${self:provider.stage}.PrivateSubnet1Id}
      - ${cf:web3-auth-infra-${self:provider.stage}.PrivateSubnet2Id}

  ecr:
    images:
      web3-auth-app:
        platform: linux/arm64
        path: ./

functions:
  api:
    image:
      name: web3-auth-app
    url: true
    timeout: 29
    memorySize: 512
    events:
      - httpApi: '*'
